ola_num_caracs: ola_num_caracs.o num_caracs.o
	gcc $(CFLAGS) -o ola_num_caracs ola_num_caracs.o num_caracs.o
main: ola_num_caracs.c num_caracs.h
	gcc $(CFLAGS) -c ola_num_caracs.c
bib: onum_caracs.c num_caracs.h
	gcc $(CFLAGS) -c num_caracs.c
clean:
	rm -f *.o ola_num_caracs
